import {
  Account,
  Transaction,
  BudgetEnvelope,
  DailyTask,
  TodayDebitItem,
  OutflowSector,
  CashflowVelocity,
  RecurringObligation,
  MindsetGoalAnchor,
  ExecutiveOverviewData,
  Project,
  WeeklyRhythmDay,
  TaskItem,
  ExecutionRhythmData,
  SystemPhase,
  TasksVelocityMetrics,
  TasksPageData,
  JournalEntry,
  ConsistencyMatrixDot,
  ConsistencyStats,
  PinnedMaxim,
  NotesPageData,
  CalendarDayCell,
  SovereignGoal,
  DayInspectorData,
  TemporalHealthMetrics,
} from '@/types/models';

export const mockAccounts: Account[] = [
  {
    id: 'acc-hdfc-4092',
    name: 'Operating Checking',
    type: 'checking',
    institution: 'HDFC Bank',
    accountNumberMasked: '•••• 4092',
    balance: 42500,
    currency: 'INR',
    status: 'active',
    trendLabel: '+2.4% vs last week',
    lastReconciledAt: '2026-09-30T18:00:00Z',
    updatedAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'acc-vault-0012',
    name: 'Physical Vault',
    type: 'cash',
    institution: 'Safe Deposit Reserve',
    accountNumberMasked: '•••• 0012',
    balance: 15200,
    currency: 'INR',
    status: 'reconciled',
    trendLabel: 'Stable allocation',
    lastReconciledAt: '2026-09-28T12:00:00Z',
    updatedAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'acc-tbill-8831',
    name: 'High-Yield Liquid Vault',
    type: 'savings',
    institution: 'Treasury Bills & Liquid Funds',
    accountNumberMasked: '•••• 8831',
    balance: 40000,
    currency: 'INR',
    status: 'active',
    trendLabel: '+4.2% APY Yield',
    lastReconciledAt: '2026-09-30T18:00:00Z',
    updatedAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'acc-amex-1042',
    name: 'Amex Platinum Card',
    type: 'credit',
    institution: 'American Express',
    accountNumberMasked: '•••• 1042',
    balance: -18500,
    currency: 'INR',
    creditLimit: 150000,
    paymentDueDate: '2026-10-05',
    status: 'active',
    trendLabel: '12% Utilized',
    lastReconciledAt: '2026-10-01T06:00:00Z',
    updatedAt: '2026-10-01T08:30:00Z',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-001',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -380,
    currency: 'INR',
    flowType: 'outflow',
    category: 'food_dining',
    categoryLabel: 'Food & Dining',
    payeeOrPayer: 'Blue Tokai Coffee Roasters',
    note: 'Morning cortado & pour-over beans',
    date: '2026-10-01',
    time: '08:15',
    paymentMethod: 'upi',
    status: 'cleared',
    createdAt: '2026-10-01T08:15:00Z',
  },
  {
    id: 'tx-002',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -420,
    currency: 'INR',
    flowType: 'outflow',
    category: 'transport_transit',
    categoryLabel: 'Transport & Transit',
    payeeOrPayer: 'Uber Premium Transit',
    note: 'Client strategy meeting transfer',
    date: '2026-10-01',
    time: '09:30',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-10-01T09:30:00Z',
  },
  {
    id: 'tx-003',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -500,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'Kinokuniya Book Order',
    note: 'Architecture of Complex Systems text',
    date: '2026-10-01',
    time: '11:45',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-10-01T11:45:00Z',
  },
  {
    id: 'tx-004',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: 45000,
    currency: 'INR',
    flowType: 'inflow',
    category: 'consulting_inflow',
    categoryLabel: 'Consulting Inflow',
    payeeOrPayer: 'Lumina Labs Advisory',
    note: 'Q3 Enterprise Architecture Retainer',
    date: '2026-09-30',
    time: '14:00',
    paymentMethod: 'direct_deposit',
    status: 'cleared',
    createdAt: '2026-09-30T14:00:00Z',
  },
  {
    id: 'tx-005',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -3850,
    currency: 'INR',
    flowType: 'outflow',
    category: 'food_dining',
    categoryLabel: 'Food & Dining',
    payeeOrPayer: 'Nature Basket Organic Market',
    note: 'Weekly organic produce & provisions',
    date: '2026-09-30',
    time: '18:20',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-09-30T18:20:00Z',
  },
  {
    id: 'tx-006',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -24000,
    currency: 'INR',
    flowType: 'outflow',
    category: 'housing_utilities',
    categoryLabel: 'Housing & Utilities',
    payeeOrPayer: 'Central Urban Studio Lease',
    note: 'Residential lease payment - September',
    date: '2026-09-28',
    time: '10:00',
    paymentMethod: 'wire',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-28T10:00:00Z',
  },
  {
    id: 'tx-007',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -4200,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'AWS Cloud Services',
    note: 'Compute & Database Infrastructure',
    date: '2026-09-27',
    time: '15:30',
    paymentMethod: 'card',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-27T15:30:00Z',
  },
  {
    id: 'tx-008',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -2100,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'Bloomberg Terminal Lite',
    note: 'Financial research data feed',
    date: '2026-09-25',
    time: '09:00',
    paymentMethod: 'card',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-25T09:00:00Z',
  },
  {
    id: 'tx-009',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -11700,
    currency: 'INR',
    flowType: 'outflow',
    category: 'shopping_gear',
    categoryLabel: 'Shopping & Gear',
    payeeOrPayer: 'Bang & Olufsen Atelier',
    note: 'Studio sound acoustic equipment',
    date: '2026-09-24',
    time: '16:15',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-09-24T16:15:00Z',
  },
  {
    id: 'tx-010',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -7800,
    currency: 'INR',
    flowType: 'outflow',
    category: 'health_wellness',
    categoryLabel: 'Health & Wellness',
    payeeOrPayer: 'Equinox Athletic Club',
    note: 'Quarterly athletic recovery & trainer',
    date: '2026-09-20',
    time: '07:30',
    paymentMethod: 'wire',
    status: 'cleared',
    createdAt: '2026-09-20T07:30:00Z',
  },
  {
    id: 'tx-011',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: 75000,
    currency: 'INR',
    flowType: 'inflow',
    category: 'consulting_inflow',
    categoryLabel: 'Consulting Inflow',
    payeeOrPayer: 'Apex Capital Advisory',
    note: 'Executive Systems Architecture Audit',
    date: '2026-09-15',
    time: '11:00',
    paymentMethod: 'wire',
    status: 'cleared',
    createdAt: '2026-09-15T11:00:00Z',
  },
  {
    id: 'tx-012',
    accountId: 'acc-vault-0012',
    accountName: 'Physical Vault',
    amount: -2500,
    currency: 'INR',
    flowType: 'outflow',
    category: 'transport_transit',
    categoryLabel: 'Transport & Transit',
    payeeOrPayer: 'Regional Chauffeur Service',
    note: 'Airport transit round-trip',
    date: '2026-09-12',
    time: '06:00',
    paymentMethod: 'cash',
    status: 'reconciled',
    createdAt: '2026-09-12T06:00:00Z',
  },
  {
    id: 'tx-013',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -365,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'Apple One Premier',
    note: 'Cloud storage and developer ecosystem',
    date: '2026-09-10',
    time: '12:00',
    paymentMethod: 'card',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-10T12:00:00Z',
  },
];

export const mockOutflowSectors: OutflowSector[] = [
  {
    id: 'sector-food',
    category: 'food_dining',
    label: 'Food & Dining',
    percentage: 30,
    amount: 19500,
    currency: 'INR',
    color: '#5F9277', // Controlled Sage
    strokeDashArray: '188.5 440',
    strokeDashOffset: 0,
  },
  {
    id: 'sector-housing',
    category: 'housing_utilities',
    label: 'Housing & Utilities',
    percentage: 25,
    amount: 16250,
    currency: 'INR',
    color: '#40617E', // Slate Secondary
    strokeDashArray: '157.1 471.2',
    strokeDashOffset: -188.5,
  },
  {
    id: 'sector-shopping',
    category: 'shopping_gear',
    label: 'Shopping & Gear',
    percentage: 18,
    amount: 11700,
    currency: 'INR',
    color: '#C76D68', // Soft Coral
    strokeDashArray: '113.1 515.2',
    strokeDashOffset: -345.6,
  },
  {
    id: 'sector-transport',
    category: 'transport_transit',
    label: 'Transport & Transit',
    percentage: 15,
    amount: 9750,
    currency: 'INR',
    color: '#C4934A', // Warm Ochre
    strokeDashArray: '94.2 534.1',
    strokeDashOffset: -458.7,
  },
  {
    id: 'sector-health',
    category: 'health_wellness',
    label: 'Health & Wellness',
    percentage: 12,
    amount: 7800,
    currency: 'INR',
    color: '#508E8C', // Mineral Teal
    strokeDashArray: '75.4 552.9',
    strokeDashOffset: -552.9,
  },
];

export const mockBudgetEnvelopes: BudgetEnvelope[] = [
  {
    id: 'env-food',
    category: 'food_dining',
    label: 'Food & Dining',
    allocatedAmount: 22000,
    spentAmount: 19500,
    currency: 'INR',
    burnRateStatus: 'normal',
    burnPercentage: 88.6,
    bufferRemaining: 2500,
    cycle: 'September 2026',
    icon: 'restaurant',
  },
  {
    id: 'env-housing',
    category: 'housing_utilities',
    label: 'Housing & Utilities',
    allocatedAmount: 25000,
    spentAmount: 24000,
    currency: 'INR',
    burnRateStatus: 'alert',
    burnPercentage: 96.0,
    bufferRemaining: 1000,
    cycle: 'September 2026',
    icon: 'home',
  },
  {
    id: 'env-shopping',
    category: 'shopping_gear',
    label: 'Shopping & Gear',
    allocatedAmount: 12500,
    spentAmount: 11700,
    currency: 'INR',
    burnRateStatus: 'alert',
    burnPercentage: 93.6,
    bufferRemaining: 800,
    cycle: 'September 2026',
    icon: 'shopping_bag',
  },
  {
    id: 'env-knowledge',
    category: 'knowledge_subs',
    label: 'Knowledge & Subs',
    allocatedAmount: 8000,
    spentAmount: 6300,
    currency: 'INR',
    burnRateStatus: 'contained',
    burnPercentage: 78.8,
    bufferRemaining: 1700,
    cycle: 'September 2026',
    icon: 'auto_stories',
  },
];

export const mockDailyTasks: DailyTask[] = [
  {
    id: 'task-1',
    title: 'Review Q3 Tax Provisioning & T-Bill Roll',
    category: 'finance',
    categoryLabel: 'Finance',
    priority: 'high',
    isCompleted: true,
    dueInfo: 'Completed 08:30 AM',
    createdAt: '2026-10-01T07:00:00Z',
    completedAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'task-2',
    title: 'Approve Lumina Labs Architectural Handoff',
    category: 'work',
    categoryLabel: 'Engineering',
    priority: 'high',
    isCompleted: true,
    dueInfo: 'Completed 09:15 AM',
    createdAt: '2026-10-01T07:15:00Z',
    completedAt: '2026-10-01T09:15:00Z',
  },
  {
    id: 'task-3',
    title: 'Reconcile HDFC & Amex Statement Feeds',
    category: 'finance',
    categoryLabel: 'Finance',
    priority: 'high',
    isCompleted: true,
    dueInfo: 'Completed 10:00 AM',
    createdAt: '2026-10-01T07:30:00Z',
    completedAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Deep Work: Anchor OS Component Architecture',
    category: 'work',
    categoryLabel: 'Engineering',
    priority: 'medium',
    isCompleted: false,
    dueInfo: 'Due 4:00 PM',
    createdAt: '2026-10-01T08:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Evening Mobility & Sprint Session',
    category: 'personal',
    categoryLabel: 'Wellness',
    priority: 'low',
    isCompleted: false,
    dueInfo: 'Due 6:30 PM',
    createdAt: '2026-10-01T08:00:00Z',
  },
];

export const mockTodayDebits: TodayDebitItem[] = [
  {
    id: 'debit-1',
    title: 'Blue Tokai Coffee Roasters',
    category: 'Food & Dining',
    paymentMethod: 'UPI • HDFC',
    amount: 380,
    currency: 'INR',
    time: '08:15 AM',
    icon: 'local_cafe',
  },
  {
    id: 'debit-2',
    title: 'Uber Premium Transit',
    category: 'Transport',
    paymentMethod: 'Card • Amex',
    amount: 420,
    currency: 'INR',
    time: '09:30 AM',
    icon: 'directions_car',
  },
  {
    id: 'debit-3',
    title: 'Kinokuniya Book Order',
    category: 'Knowledge',
    paymentMethod: 'Card • HDFC',
    amount: 500,
    currency: 'INR',
    time: '11:45 AM',
    icon: 'menu_book',
  },
];

export const mockMindsetGoal: MindsetGoalAnchor = {
  quote: 'Discipline is choosing between what you want now and what you want most.',
  quoteAuthor: 'Auguste Comte / Vance Journal',
  entryTime: 'Logged Today at 07:15 AM',
  goalTitle: 'Annual Tactical Reserve Fund',
  targetAmount: 100000,
  currentAmount: 72000,
  achievedPercentage: 72,
  targetDate: 'Dec 31, 2026',
};

export const mockCashflowVelocity: CashflowVelocity = {
  cycleDay: 21,
  cycleTotalDays: 30,
  totalInflow: 120000,
  totalOutflow: 65000,
  netSavings: 55000,
  retentionRate: 45.8,
  targetRetentionRate: 50.0,
  inflowCount: 3,
  outflowCount: 38,
  hotspots: [
    {
      id: 'hotspot-1',
      title: 'Dining out velocity',
      metric: '+18% vs 30-day baseline',
      severity: 'warning',
    },
    {
      id: 'hotspot-2',
      title: 'Ad hoc ride-hailing pace',
      metric: 'Rs. 2,100 / week velocity',
      severity: 'info',
    },
    {
      id: 'hotspot-3',
      title: 'Upcoming SaaS renewals',
      metric: '2 services renewing in 7 days',
      severity: 'warning',
    },
  ],
};

export const mockRecurringObligations: RecurringObligation[] = [
  {
    id: 'rec-1',
    name: 'AWS Cloud Services',
    amount: 4200,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 4 days',
    status: 'alert',
    category: 'knowledge_subs',
    icon: 'cloud',
  },
  {
    id: 'rec-2',
    name: 'Bloomberg Terminal Lite',
    amount: 2100,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 12 days',
    status: 'upcoming',
    category: 'knowledge_subs',
    icon: 'query_stats',
  },
  {
    id: 'rec-3',
    name: 'Residential Lease - Urban Studio',
    amount: 24000,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 28 days',
    status: 'cleared',
    category: 'housing_utilities',
    icon: 'apartment',
  },
  {
    id: 'rec-4',
    name: 'Apple One Premier Ecosystem',
    amount: 365,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 8 days',
    status: 'upcoming',
    category: 'knowledge_subs',
    icon: 'devices',
  },
];

export const mockOverviewData: ExecutiveOverviewData = {
  greeting: 'Good morning, Alex.',
  userName: 'Alex Vance',
  systemStatus: 'steady',
  dateDisplay: 'Thursday, October 1, 2026',
  totalLiquidity: 79200,
  liquidityTrendPercent: 4.2,
  currency: 'INR',
  monthlyInflow: 120000,
  monthlyInflowTrendPercent: 8.5,
  inflowSourcesCount: 3,
  totalExpenses: 65000,
  expensesBurnRatePercent: 81.2,
  netRetained: 55000,
  retentionRatePercent: 45.8,
  outflowSectors: mockOutflowSectors,
  totalSpent: 65000,
  budgetCap: 70000,
  budgetEnvelopes: mockBudgetEnvelopes,
  dailyTasks: mockDailyTasks,
  todayDebits: mockTodayDebits,
  mindsetGoal: mockMindsetGoal,
};

// ----------------------------------------------------------------------------
// Tasks & Projects Command Center Mock Fixtures
// ----------------------------------------------------------------------------

export const mockWeeklyRhythm: WeeklyRhythmDay[] = [
  { day: 'M', heightPercent: 60, isToday: false },
  { day: 'T', heightPercent: 75, isToday: false },
  { day: 'W', heightPercent: 100, isToday: true },
  { day: 'T', heightPercent: 40, isToday: false },
  { day: 'F', heightPercent: 50, isToday: false },
  { day: 'S', heightPercent: 20, isToday: false },
  { day: 'S', heightPercent: 15, isToday: false },
];

export const mockExecutionRhythm: ExecutionRhythmData = {
  allocatedTimeRange: '2:30 PM — 4:00 PM',
  title: 'Rhythm Guardrail',
  description:
    'Deep work block allocated for 2:30 PM — 4:00 PM. No context switching permitted during the TypeScript performance audit.',
  blockName: 'TypeScript performance audit',
  focusMode: true,
};

export const mockActiveProjects: Project[] = [
  {
    id: 'proj-anchor',
    title: 'Personal Life Management (ANCHOR)',
    tag: 'SYSTEMS ARCHITECTURE',
    description: 'Autonomous executive dashboard, ledger tracking & cognitive workspace.',
    progressPercentage: 72,
    nextMilestone: 'Beta Deployment',
    tasksCompleted: 8,
    totalTasks: 11,
    accentColor: '#274a65',
  },
  {
    id: 'proj-nextjs',
    title: 'Next.js 15 & System Architecture',
    tag: 'ENGINEERING',
    description: 'Turbopack compiler benchmarking, React 19 server components baseline.',
    progressPercentage: 45,
    nextMilestone: 'App Router audit',
    tasksCompleted: 9,
    totalTasks: 20,
    accentColor: '#3F6853',
  },
  {
    id: 'proj-sovereign',
    title: 'Q4 Sovereign Reserve Strategy',
    tag: 'CAPITAL PRESERVATION',
    description: 'Multi-custody allocation, treasury laddering and risk liquidity review.',
    progressPercentage: 85,
    nextMilestone: 'Dec 31, 2024',
    targetDate: 'Dec 31, 2024',
    tasksCompleted: 6,
    totalTasks: 7,
    accentColor: '#7A5B10',
  },
];

export const mockSystemPhases: SystemPhase[] = [
  { id: 'phase-1', name: 'Phase I: Foundation', status: 'completed' },
  { id: 'phase-2', name: 'Phase II: Scaling (Active)', status: 'active' },
  { id: 'phase-3', name: 'Phase III: Hardening', status: 'upcoming' },
];

export const mockTaskItems: TaskItem[] = [
  {
    id: 'task-stitch-1',
    title: 'Complete API integration',
    isCompleted: true,
    priority: 'high',
    category: 'Engineering',
    categoryLabel: 'Engineering',
    statusBadge: 'Done',
    dueInfo: 'Due 2:00 PM',
    dueTime: '2:00 PM',
    dueDate: 'Today',
    projectId: 'proj-anchor',
    projectName: 'Personal Life Management (ANCHOR)',
    metaPill: 'Engineering',
    tabCategory: 'today',
    createdAt: '2026-10-23T08:00:00Z',
    completedAt: '2026-10-23T09:15:00Z',
  },
  {
    id: 'task-stitch-2',
    title: 'Morning gym session',
    isCompleted: true,
    priority: 'low',
    category: 'Personal',
    categoryLabel: 'Health',
    statusBadge: 'Done 8:30 AM',
    dueInfo: '75 min workout',
    dueTime: '8:30 AM',
    dueDate: 'Today',
    projectId: 'inbox',
    projectName: 'Unassigned / Inbox',
    metaPill: 'Health',
    tabCategory: 'today',
    createdAt: '2026-10-23T07:00:00Z',
    completedAt: '2026-10-23T08:30:00Z',
  },
  {
    id: 'task-stitch-3',
    title: 'Review monthly investment yield',
    isCompleted: true,
    priority: 'medium',
    category: 'Finance',
    categoryLabel: 'Portfolio',
    statusBadge: 'Done 11:00 AM',
    dueInfo: 'Yield +3.8%',
    dueTime: '11:00 AM',
    dueDate: 'Today',
    projectId: 'proj-sovereign',
    projectName: 'Q4 Sovereign Reserve Strategy',
    metaPill: 'Portfolio',
    tabCategory: 'today',
    createdAt: '2026-10-23T07:30:00Z',
    completedAt: '2026-10-23T11:00:00Z',
  },
  {
    id: 'task-stitch-4',
    title: 'Study TypeScript 5.5 performance notes',
    isCompleted: false,
    priority: 'medium',
    category: 'Learning',
    categoryLabel: 'Architecture',
    statusBadge: 'Learning',
    dueInfo: 'Est. 45 min',
    dueTime: '4:00 PM',
    dueDate: 'Today',
    projectId: 'proj-nextjs',
    projectName: 'Next.js 15 & System Architecture',
    metaPill: 'Architecture',
    estimatedMinutes: 45,
    isFocusBlock: true,
    tabCategory: 'today',
    createdAt: '2026-10-23T08:00:00Z',
  },
  {
    id: 'task-stitch-5',
    title: 'Weekly financial ledger reconciliation',
    isCompleted: false,
    priority: 'high',
    category: 'Finance',
    categoryLabel: 'Finance',
    statusBadge: 'HIGH',
    dueInfo: 'Due 6:00 PM',
    dueTime: '6:00 PM',
    dueDate: 'Today',
    projectId: 'proj-sovereign',
    projectName: 'Q4 Sovereign Reserve Strategy',
    metaPill: 'Vault Audit',
    tabCategory: 'today',
    createdAt: '2026-10-23T08:30:00Z',
  },
  {
    id: 'task-stitch-6',
    title: 'Draft Q4 engineering roadmap',
    isCompleted: false,
    priority: 'medium',
    category: 'Projects',
    categoryLabel: 'Work',
    statusBadge: 'Due Tomorrow',
    dueInfo: 'Milestone V2',
    dueTime: '10:00 AM',
    dueDate: 'Tomorrow',
    projectId: 'proj-anchor',
    projectName: 'Personal Life Management (ANCHOR)',
    metaPill: 'Milestone V2',
    tabCategory: 'upcoming',
    createdAt: '2026-10-23T09:00:00Z',
  },
  {
    id: 'task-overdue-1',
    title: 'Archive deprecated v1 API telemetry',
    isCompleted: false,
    priority: 'high',
    category: 'Engineering',
    categoryLabel: 'Maintenance',
    statusBadge: 'Overdue',
    dueInfo: 'Overdue by 2 days',
    dueTime: '5:00 PM',
    dueDate: 'Oct 21',
    projectId: 'proj-nextjs',
    projectName: 'Next.js 15 & System Architecture',
    metaPill: 'Legacy Clean',
    tabCategory: 'overdue',
    createdAt: '2026-10-21T09:00:00Z',
  },
  {
    id: 'task-backlog-1',
    title: 'Multisig key rotation & cold vault drill',
    isCompleted: false,
    priority: 'low',
    category: 'Finance',
    categoryLabel: 'Security',
    statusBadge: 'Backlog',
    dueInfo: 'Q4 Backlog',
    dueTime: 'TBD',
    dueDate: 'End of Q4',
    projectId: 'proj-sovereign',
    projectName: 'Q4 Sovereign Reserve Strategy',
    metaPill: 'SecOps',
    tabCategory: 'backlog',
    createdAt: '2026-10-15T09:00:00Z',
  },
];

export const mockVelocityMetrics: TasksVelocityMetrics = {
  completedCount: 5,
  weeklyAverageDelta: '+20% vs 7-day average',
  weeklyRhythm: mockWeeklyRhythm,
  syncStatus: 'Real-time',
  syncLatencyMs: 224,
};

export const mockTasksPageData: TasksPageData = {
  tasks: mockTaskItems,
  activeProjects: mockActiveProjects,
  weeklyRhythm: mockWeeklyRhythm,
  executionRhythm: mockExecutionRhythm,
  velocityMetrics: mockVelocityMetrics,
  systemPhases: mockSystemPhases,
};

// ----------------------------------------------------------------------------
// Daily Notes & Reflective Journal Workspace Fixtures
// ----------------------------------------------------------------------------

export const mockJournalEntries: JournalEntry[] = [
  {
    id: 'entry-sep-11',
    dateKey: '2026-09-11',
    date: 'Sep 11 (Today)',
    dateDisplay: 'Sep 11 (Today)',
    dateShort: 'Sep 11',
    dateFullFormatted: 'Friday, September 11, 2026',
    dayNumber: 11,
    dayOfWeek: 'FRI',
    isToday: true,
    entryNumber: 254,
    title: 'Stabilizing the core pipelines & emotional grounding',
    snippet: 'Reviewed treasury position, re-factored system invariants, and held steady through market noise...',
    wordCount: 480,
    readingTimeMinutes: 6,
    linksCount: 3,
    moodTag: 'Grounded',
    moodColor: '#3F6853',
    mood: {
      tag: 'Grounded',
      label: 'Grounded & Focused',
      color: '#3F6853',
      bgColor: 'rgba(95, 146, 119, 0.15)',
      dotColor: '#5F9277',
    },
    inquiryQuestion: 'How was today? What did you refrain from reacting to?',
    inquiryAnswered: true,
    inquiry: {
      id: 'inq-sep-11',
      question: 'How was today? What did you refrain from reacting to?',
      isAnswered: true,
      answer: 'Instituted an immediate 90-minute blackout buffer right after morning review. Discharged anxiety before committing changes.',
      assessedAt: '20:45',
      toneAssessment: 'Assessed at 20:45 across focus, energy, and decision clarity.',
      statusBadge: 'Answered',
    },
    contentParagraphs: [
      'The morning opened with turbulent alerts across our external infrastructure integrations. In past years, this would have instigated an acute adrenaline spike—a rushed cascade of meetings, reactive slack threads, and immediate architectural compromises. Today, I practiced measured stillness.',
      'By noon, the core pipelines were insulated. We decoupled the redundant listeners and consolidated our internal database write-locks into single sovereign batches. What felt like an existential fire was reduced to four clean lines of configuration adjustments.',
      'There is an unmistakable clarity that emerges when you decide what not to attend to. Fluidity returned once the unnecessary operational overhead was purged.',
    ],
    quote: 'Agitation is expensive. The clearest answers emerge only after you allow the sediment of initial anxiety to settle to the bottom.',
    quoteAttribution: 'Anchor Ledger Codex · Axiom 04',
    observations: [
      {
        title: 'Capital calm:',
        note: 'Executed standard monthly rebalance without yielding to the impulse to over-hedge.',
      },
      {
        title: 'Physical baseline:',
        note: '45-minute evening walk along the reservoir; cognitive load noticeably discharged.',
      },
      {
        title: "Tomorrow's rule:",
        note: 'Guard the morning 3-hour uninterrupted block for ANCHOR database schema hardening.',
      },
    ],
    microObservations: {
      time: '21:15',
      items: [
        'Eliminated context switching across three distinct workspaces.',
        'Liquid reserves rebalanced cleanly into conservative short yields.',
        'Physical stamina maintained through disciplined afternoon hiatus.',
      ],
    },
    linkedEntities: {
      project: { id: 'proj-anchor', name: 'ANCHOR Core', type: 'Core System' },
      financialDebit: { amount: 1300, currency: 'INR', formattedText: 'Rs. 1,300', subtitle: '-Rs. 1,300 spent today' },
      tasksResolved: { count: 3, resolvedCount: 3, formattedText: '3 tasks checked' },
    },
    linkedProject: { name: 'ANCHOR Core', type: 'Core System' },
    linkedDebit: { amount: 1300, currency: 'INR' },
    linkedTasksResolvedCount: 3,
    loggedTimeInfo: 'Logged at 21:40 EST · Quiet Office · Room temp 20°C',
    tags: ['#engineering', '#finance', '#clarity', '#mindset'],
    isPinned: true,
    createdAt: '2026-09-11T21:40:00Z',
    updatedAt: '2026-09-11T21:40:00Z',
  },
  {
    id: 'entry-sep-10',
    dateKey: '2026-09-10',
    date: 'Sep 10',
    dateDisplay: 'Sep 10',
    dateShort: 'Sep 10',
    dateFullFormatted: 'Thursday, September 10, 2026',
    dayNumber: 10,
    dayOfWeek: 'THU',
    isToday: false,
    entryNumber: 253,
    title: 'Restraint as leverage: on capital discipline',
    snippet: 'Allocating margin rather than chasing upside during volatility.',
    wordCount: 620,
    readingTimeMinutes: 7,
    linksCount: 2,
    moodTag: 'Strategic',
    moodColor: '#40617E',
    mood: {
      tag: 'Strategic',
      label: 'Strategic Leverage',
      color: '#40617E',
      bgColor: '#cde5ff',
      dotColor: '#40617E',
    },
    inquiryQuestion: 'Where did you say no to preserve sovereignty?',
    inquiryAnswered: true,
    inquiry: {
      id: 'inq-sep-10',
      question: 'Where did you say no to preserve sovereignty?',
      isAnswered: true,
      answer: 'Turned down two advisory calls that offered near-term compensation but threatened Q4 deep architecture focus.',
      assessedAt: '21:00',
      toneAssessment: 'Assessed at 21:00 across capital conservation and cognitive bandwidth.',
      statusBadge: 'Answered',
    },
    contentParagraphs: [
      'Capital discipline is rarely about aggressive accumulation; it is fundamentally about asymmetry of patience. When the market experiences transient dislocations, the impulse to act is an emotional tax.',
      'By strictly locking liquidity buffers into 91-day sovereign instruments, we remove the temptation to optimize for marginal percentage gains at the expense of total solvency peace of mind.',
    ],
    quote: 'Restraint is power. When life gets chaotic, tighten the system.',
    quoteAttribution: 'Capital Allocation Directives',
    observations: [
      {
        title: 'Treasury positioning:',
        note: 'Maintained 40k buffer in High-Yield vault without speculative redeployment.',
      },
      {
        title: 'Cognitive defense:',
        note: 'Zero social media or finance feeds consumed before noon.',
      },
    ],
    microObservations: {
      time: '21:30',
      items: [
        'Protected morning hours from ad-hoc investor queries.',
        'Audited quarterly fixed liabilities and trimmed redundant SaaS seat.',
        'Restored clarity through 60-minute resistance training.',
      ],
    },
    linkedEntities: {
      project: { id: 'proj-sovereign', name: 'Q4 Sovereign Reserve Strategy', type: 'Capital' },
      financialDebit: { amount: 420, currency: 'INR', formattedText: 'Rs. 420', subtitle: 'Transit & Logistics' },
      tasksResolved: { count: 2, resolvedCount: 2, formattedText: '2 tasks checked' },
    },
    linkedProject: { name: 'Q4 Sovereign Reserve Strategy', type: 'Capital' },
    linkedDebit: { amount: 420, currency: 'INR' },
    linkedTasksResolvedCount: 2,
    loggedTimeInfo: 'Logged at 22:10 EST · Library Study · Room temp 21°C',
    tags: ['#finance', '#mindset', '#clarity'],
    isPinned: true,
    createdAt: '2026-09-10T22:10:00Z',
    updatedAt: '2026-09-10T22:10:00Z',
  },
  {
    id: 'entry-sep-09',
    dateKey: '2026-09-09',
    date: 'Sep 09',
    dateDisplay: 'Sep 09',
    dateShort: 'Sep 09',
    dateFullFormatted: 'Wednesday, September 09, 2026',
    dayNumber: 9,
    dayOfWeek: 'WED',
    isToday: false,
    entryNumber: 252,
    title: 'Quarterly advisory retrospective',
    snippet: 'Notes from conversations with Marcus and Elena on long-term sovereignty.',
    wordCount: 890,
    readingTimeMinutes: 9,
    linksCount: 4,
    moodTag: 'Review',
    moodColor: '#45474c',
    mood: {
      tag: 'Review',
      label: 'Quarterly Retrospective',
      color: '#45474c',
      bgColor: '#eae8e2',
      dotColor: '#75777d',
    },
    inquiryQuestion: 'What structural blind spot became apparent today?',
    inquiryAnswered: true,
    inquiry: {
      id: 'inq-sep-09',
      question: 'What structural blind spot became apparent today?',
      isAnswered: true,
      answer: 'Identified that operational dependency on single-point cloud services creates unacceptable systemic fragility.',
      assessedAt: '19:45',
      toneAssessment: 'Assessed at 19:45 across architectural sovereignty.',
      statusBadge: 'Answered',
    },
    contentParagraphs: [
      'Marcus brought up an uncomfortable truth during our afternoon sync: our perceived autonomy is only as robust as our supply chain dependencies. If an API provider changes terms or shutters service, our cadence halts.',
      'Elena concurred, advocating for a local-first offline architecture for ANCHOR where local SQLite or flat JSON files remain authoritative, with cloud services functioning solely as dumb sync mirrors.',
    ],
    quote: 'Sovereignty is not isolation; it is the decoupling of survival from external goodwill.',
    quoteAttribution: 'System Principles v1',
    observations: [
      {
        title: 'Architectural alignment:',
        note: 'Committing to zero external tracking and offline-first storage.',
      },
      {
        title: 'Advisory synthesis:',
        note: 'Clear mandate to prioritize data portability over flashy ecosystem lock-ins.',
      },
    ],
    microObservations: {
      time: '20:15',
      items: [
        'Detailed 4-page review document compiled for Marcus & Elena.',
        'Local data storage benchmark completed at sub-5ms latency.',
        'Evening meditation session completed without interruption.',
      ],
    },
    linkedEntities: {
      project: { id: 'proj-anchor', name: 'Personal Life Management (ANCHOR)', type: 'Architecture' },
      financialDebit: { amount: 500, currency: 'INR', formattedText: 'Rs. 500', subtitle: 'Kinokuniya Book Order' },
      tasksResolved: { count: 4, resolvedCount: 4, formattedText: '4 tasks checked' },
    },
    linkedProject: { name: 'Personal Life Management (ANCHOR)', type: 'Architecture' },
    linkedDebit: { amount: 500, currency: 'INR' },
    linkedTasksResolvedCount: 4,
    loggedTimeInfo: 'Logged at 20:30 EST · Home Desk · Room temp 22°C',
    tags: ['#engineering', '#clarity', '#mindset'],
    isPinned: false,
    createdAt: '2026-09-09T20:30:00Z',
    updatedAt: '2026-09-09T20:30:00Z',
  },
  {
    id: 'entry-sep-08',
    dateKey: '2026-09-08',
    date: 'Sep 08',
    dateDisplay: 'Sep 08',
    dateShort: 'Sep 08',
    dateFullFormatted: 'Tuesday, September 08, 2026',
    dayNumber: 8,
    dayOfWeek: 'TUE',
    isToday: false,
    entryNumber: 251,
    title: 'Architecture decisions and system simplicity',
    snippet: 'Cutting third-party telemetry in favor of sovereign flat-file logs.',
    wordCount: 510,
    readingTimeMinutes: 5,
    linksCount: 1,
    moodTag: 'Systems',
    moodColor: '#0B1628',
    mood: {
      tag: 'Systems',
      label: 'Systems Simplicity',
      color: '#0B1628',
      bgColor: '#e4e2dd',
      dotColor: '#0B1628',
    },
    inquiryQuestion: 'What complexity did you successfully eliminate today?',
    inquiryAnswered: true,
    inquiry: {
      id: 'inq-sep-08',
      question: 'What complexity did you successfully eliminate today?',
      isAnswered: true,
      answer: 'Purged three bloated npm dependencies and replaced them with standard web crypto and native fetch.',
      assessedAt: '20:00',
      toneAssessment: 'Assessed at 20:00 across codebase minimalism.',
      statusBadge: 'Answered',
    },
    contentParagraphs: [
      'Every third-party dependency imported into a project is an unvetted mortgage taken out against your future cognitive peace. Today we eliminated three external analytics libraries in favor of local structured JSON lines.',
      'The binary build size decreased by 34%, cold boot time dropped under 120ms, and most importantly, our attack surface shrank to near-zero.',
    ],
    quote: 'Simplicity is prerequisite for reliability.',
    quoteAttribution: 'Edsger W. Dijkstra',
    observations: [
      {
        title: 'Code audit:',
        note: 'Replaced telemetry SDK with 15-line custom structured logger.',
      },
      {
        title: 'Performance telemetry:',
        note: 'Sub-millisecond write times recorded on local SSD.',
      },
    ],
    microObservations: {
      time: '21:00',
      items: [
        'Uninstalled redundant telemetry npm packages.',
        'Documented zero-leak data collection policy.',
        'Completed evening mobility drills.',
      ],
    },
    linkedEntities: {
      project: { id: 'proj-nextjs', name: 'Next.js 15 & System Architecture', type: 'Engineering' },
      financialDebit: { amount: 380, currency: 'INR', formattedText: 'Rs. 380', subtitle: 'Coffee & Sustenance' },
      tasksResolved: { count: 3, resolvedCount: 3, formattedText: '3 tasks checked' },
    },
    linkedProject: { name: 'Next.js 15 & System Architecture', type: 'Engineering' },
    linkedDebit: { amount: 380, currency: 'INR' },
    linkedTasksResolvedCount: 3,
    loggedTimeInfo: 'Logged at 21:15 EST · Terminal Console · Room temp 20°C',
    tags: ['#engineering', '#clarity'],
    isPinned: false,
    createdAt: '2026-09-08T21:15:00Z',
    updatedAt: '2026-09-08T21:15:00Z',
  },
  {
    id: 'entry-sep-07',
    dateKey: '2026-09-07',
    date: 'Sep 07',
    dateDisplay: 'Sep 07',
    dateShort: 'Sep 07',
    dateFullFormatted: 'Monday, September 07, 2026',
    dayNumber: 7,
    dayOfWeek: 'MON',
    isToday: false,
    entryNumber: 250,
    title: 'Weekly review & energetic audit',
    snippet: 'Audit of hours spent in deep work versus operational drag.',
    wordCount: 740,
    readingTimeMinutes: 8,
    linksCount: 2,
    moodTag: 'Weekly Audit',
    moodColor: '#C4934A',
    mood: {
      tag: 'Weekly Audit',
      label: 'Weekly Operational Audit',
      color: '#C4934A',
      bgColor: '#FFF2B2',
      dotColor: '#C4934A',
    },
    inquiryQuestion: 'How did your actual time distribution match your declared values?',
    inquiryAnswered: true,
    inquiry: {
      id: 'inq-sep-07',
      question: 'How did your actual time distribution match your declared values?',
      isAnswered: true,
      answer: '22 hours in deep architecture focus, 6 hours in administrative meetings, 8 hours in physical resilience training.',
      assessedAt: '19:00',
      toneAssessment: 'Assessed at 19:00 across energy balance and output efficacy.',
      statusBadge: 'Answered',
    },
    contentParagraphs: [
      'Running the weekly retrospective audit revealed an encouraging shift: deep work blocks accounted for 64% of total awake productive hours, up from 48% in the previous audit cycle.',
      'Operational drag was primarily caused by unscheduled messaging interruptions between 14:00 and 16:00. Next week, this interval is formally designated as an asynchronous buffer zone.',
    ],
    quote: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    quoteAttribution: 'James Clear',
    observations: [
      {
        title: 'Deep work metric:',
        note: '22 verified hours logged in uninterrupted cognitive flow.',
      },
      {
        title: 'Biological recovery:',
        note: 'Average sleep duration 7.8 hours across 7 nights.',
      },
    ],
    microObservations: {
      time: '19:30',
      items: [
        'Calendar blocked for next week with strict deep work windows.',
        'Weekly financial ledger reconciled to the rupee.',
        'Physical recovery metrics green across all trackers.',
      ],
    },
    linkedEntities: {
      project: { id: 'proj-anchor', name: 'Personal Life Management (ANCHOR)', type: 'Executive' },
      financialDebit: { amount: 650, currency: 'INR', formattedText: 'Rs. 650', subtitle: 'Weekly Fuel & Logistics' },
      tasksResolved: { count: 5, resolvedCount: 5, formattedText: '5 tasks checked' },
    },
    linkedProject: { name: 'Personal Life Management (ANCHOR)', type: 'Executive' },
    linkedDebit: { amount: 650, currency: 'INR' },
    linkedTasksResolvedCount: 5,
    loggedTimeInfo: 'Logged at 19:45 EST · Standing Desk · Room temp 21°C',
    tags: ['#mindset', '#finance', '#clarity'],
    isPinned: false,
    createdAt: '2026-09-07T19:45:00Z',
    updatedAt: '2026-09-07T19:45:00Z',
  },
];

export const mockSparkMatrix: ConsistencyMatrixDot[] = [
  // Row 1: Aug 12 - Aug 21 (10 dots, dot 3 Aug 15 missed)
  { dayIndex: 0, date: '2026-08-12', label: 'Aug 12', status: 'completed', tooltipText: 'Aug 12 · Logged' },
  { dayIndex: 1, date: '2026-08-13', label: 'Aug 13', status: 'completed', tooltipText: 'Aug 13 · Logged' },
  { dayIndex: 2, date: '2026-08-14', label: 'Aug 14', status: 'completed', tooltipText: 'Aug 14 · Logged' },
  { dayIndex: 3, date: '2026-08-15', label: 'Aug 15', status: 'missed', tooltipText: 'Aug 15 · Missed day' },
  { dayIndex: 4, date: '2026-08-16', label: 'Aug 16', status: 'completed', tooltipText: 'Aug 16 · Logged' },
  { dayIndex: 5, date: '2026-08-17', label: 'Aug 17', status: 'completed', tooltipText: 'Aug 17 · Logged' },
  { dayIndex: 6, date: '2026-08-18', label: 'Aug 18', status: 'completed', tooltipText: 'Aug 18 · Logged' },
  { dayIndex: 7, date: '2026-08-19', label: 'Aug 19', status: 'completed', tooltipText: 'Aug 19 · Logged' },
  { dayIndex: 8, date: '2026-08-20', label: 'Aug 20', status: 'completed', tooltipText: 'Aug 20 · Logged' },
  { dayIndex: 9, date: '2026-08-21', label: 'Aug 21', status: 'completed', tooltipText: 'Aug 21 · Logged' },
  // Row 2: Aug 22 - Aug 31 (10 dots, dot 15 Aug 27 missed)
  { dayIndex: 10, date: '2026-08-22', label: 'Aug 22', status: 'completed', tooltipText: 'Aug 22 · Logged' },
  { dayIndex: 11, date: '2026-08-23', label: 'Aug 23', status: 'completed', tooltipText: 'Aug 23 · Logged' },
  { dayIndex: 12, date: '2026-08-24', label: 'Aug 24', status: 'completed', tooltipText: 'Aug 24 · Logged' },
  { dayIndex: 13, date: '2026-08-25', label: 'Aug 25', status: 'completed', tooltipText: 'Aug 25 · Logged' },
  { dayIndex: 14, date: '2026-08-26', label: 'Aug 26', status: 'completed', tooltipText: 'Aug 26 · Logged' },
  { dayIndex: 15, date: '2026-08-27', label: 'Aug 27', status: 'missed', tooltipText: 'Aug 27 · Missed day' },
  { dayIndex: 16, date: '2026-08-28', label: 'Aug 28', status: 'completed', tooltipText: 'Aug 28 · Logged' },
  { dayIndex: 17, date: '2026-08-29', label: 'Aug 29', status: 'completed', tooltipText: 'Aug 29 · Logged' },
  { dayIndex: 18, date: '2026-08-30', label: 'Aug 30', status: 'completed', tooltipText: 'Aug 30 · Logged' },
  { dayIndex: 19, date: '2026-08-31', label: 'Aug 31', status: 'completed', tooltipText: 'Aug 31 · Logged' },
  // Row 3: Sep 01 - Sep 11 (10 dots, dot 29 Sep 11 today)
  { dayIndex: 20, date: '2026-09-01', label: 'Sep 01', status: 'completed', tooltipText: 'Sep 01 · Logged' },
  { dayIndex: 21, date: '2026-09-02', label: 'Sep 02', status: 'completed', tooltipText: 'Sep 02 · Logged' },
  { dayIndex: 22, date: '2026-09-03', label: 'Sep 03', status: 'completed', tooltipText: 'Sep 03 · Logged' },
  { dayIndex: 23, date: '2026-09-04', label: 'Sep 04', status: 'completed', tooltipText: 'Sep 04 · Logged' },
  { dayIndex: 24, date: '2026-09-05', label: 'Sep 05', status: 'completed', tooltipText: 'Sep 05 · Logged' },
  { dayIndex: 25, date: '2026-09-06', label: 'Sep 06', status: 'completed', tooltipText: 'Sep 06 · Logged' },
  { dayIndex: 26, date: '2026-09-07', label: 'Sep 07', status: 'completed', tooltipText: 'Sep 07 · Logged' },
  { dayIndex: 27, date: '2026-09-08', label: 'Sep 08', status: 'completed', tooltipText: 'Sep 08 · Logged' },
  { dayIndex: 28, date: '2026-09-09', label: 'Sep 09', status: 'completed', tooltipText: 'Sep 09 · Logged' },
  { dayIndex: 29, date: '2026-09-11', label: 'Sep 11', status: 'today', tooltipText: 'Sep 11 · Today' },
];

export const mockConsistencyStats: ConsistencyStats = {
  scorePercentage: 94,
  momChangeDelta: '+4% MoM',
  totalDays: 30,
  startDateLabel: 'Aug 12',
  endDateLabel: 'Sep 11',
  dominantTone: 'Stoic / Analytical',
  sparkMatrix: mockSparkMatrix,
};

export const mockPinnedMaxim: PinnedMaxim = {
  id: 'maxim-01',
  quote: 'Restraint is power. When life gets chaotic, tighten the system.',
  attribution: 'Affixed to September Executive Review',
  sourceCodex: 'Anchor Ledger Codex · Axiom 04',
};

export const mockTaxonomyTags: string[] = [
  '#engineering',
  '#finance',
  '#clarity',
  '#mindset',
];

export const mockNotesPageData: NotesPageData = {
  entries: mockJournalEntries,
  activeEntry: mockJournalEntries[0],
  consistencyStats: mockConsistencyStats,
  pinnedMaxim: mockPinnedMaxim,
  taxonomyTags: mockTaxonomyTags,
  termBadge: 'Autumn Term 2026',
  currentMonth: 'September 2026',
  syncStatus: {
    lastSyncedDisplay: 'Synced 2m ago',
    isLive: true,
  },
};

// ----------------------------------------------------------------------------
// Unified Calendar & Sovereign Goals Nexus Fixtures
// ----------------------------------------------------------------------------

export const mockCalendarDays: CalendarDayCell[] = [
  // Week 1: Aug 30 - Sep 05
  { dateKey: '2026-08-30', dayNumber: 30, isCurrentMonth: false, isToday: false, monthLabel: 'Aug' },
  { dateKey: '2026-08-31', dayNumber: 31, isCurrentMonth: false, isToday: false, monthLabel: 'Aug' },
  { dateKey: '2026-09-01', dayNumber: 1, isCurrentMonth: true, isToday: false, hasJournal: true, financeAmount: 4200, tasksDone: 4, tasksTotal: 4 },
  { dateKey: '2026-09-02', dayNumber: 2, isCurrentMonth: true, isToday: false, hasJournal: false, financeAmount: -450, tasksDone: 2, tasksTotal: 3 },
  { dateKey: '2026-09-03', dayNumber: 3, isCurrentMonth: true, isToday: false, hasJournal: true, financeAmount: -890, tasksDone: 5, tasksTotal: 5 },
  { dateKey: '2026-09-04', dayNumber: 4, isCurrentMonth: true, isToday: false, hasJournal: false, financeAmount: -1120, tasksDone: 3, tasksTotal: 4 },
  { dateKey: '2026-09-05', dayNumber: 5, isCurrentMonth: true, isToday: false, hasJournal: true, financeAmount: -2400, specialNote: 'Sprint rest' },

  // Week 2: Sep 06 - Sep 12
  { dateKey: '2026-09-06', dayNumber: 6, isCurrentMonth: true, isToday: false, specialNote: 'Reflect & plan', tasksDone: 2, tasksTotal: 2 },
  { dateKey: '2026-09-07', dayNumber: 7, isCurrentMonth: true, isToday: false, hasJournal: true, financeAmount: -320, tasksDone: 4, tasksTotal: 5 },
  { dateKey: '2026-09-08', dayNumber: 8, isCurrentMonth: true, isToday: false, hasJournal: false, financeAmount: -600, tasksDone: 3, tasksTotal: 3 },
  { dateKey: '2026-09-09', dayNumber: 9, isCurrentMonth: true, isToday: false, hasJournal: true, financeAmount: 1800, tasksDone: 6, tasksTotal: 6 },
  { dateKey: '2026-09-10', dayNumber: 10, isCurrentMonth: true, isToday: false, hasJournal: false, financeAmount: -950, tasksDone: 4, tasksTotal: 4 },
  { dateKey: '2026-09-11', dayNumber: 11, isCurrentMonth: true, isToday: true, hasJournal: true, financeAmount: -1300, tasksDone: 3, tasksTotal: 5 },
  { dateKey: '2026-09-12', dayNumber: 12, isCurrentMonth: true, isToday: false, specialNote: 'Deep Work Block', tasksDone: 1, tasksTotal: 2 },

  // Week 3: Sep 13 - Sep 19
  { dateKey: '2026-09-13', dayNumber: 13, isCurrentMonth: true, isToday: false, specialNote: 'Rest & Strategy' },
  { dateKey: '2026-09-14', dayNumber: 14, isCurrentMonth: true, isToday: false, financeAmount: -250, specialNote: '3 tasks slated' },
  { dateKey: '2026-09-15', dayNumber: 15, isCurrentMonth: true, isToday: false, hasJournal: false, financeAmount: 15000, specialNote: 'Dividend Influx' },
  { dateKey: '2026-09-16', dayNumber: 16, isCurrentMonth: true, isToday: false, specialNote: 'System Audit' },
  { dateKey: '2026-09-17', dayNumber: 17, isCurrentMonth: true, isToday: false, specialNote: '4 tasks slated' },
  { dateKey: '2026-09-18', dayNumber: 18, isCurrentMonth: true, isToday: false, specialNote: 'Quarterly Review' },
  { dateKey: '2026-09-19', dayNumber: 19, isCurrentMonth: true, isToday: false, specialNote: 'Off-grid Session' },

  // Week 4: Sep 20 - Sep 26
  { dateKey: '2026-09-20', dayNumber: 20, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-21', dayNumber: 21, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-22', dayNumber: 22, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-23', dayNumber: 23, isCurrentMonth: true, isToday: false, specialNote: 'Autopay Cycle' },
  { dateKey: '2026-09-24', dayNumber: 24, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-25', dayNumber: 25, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-26', dayNumber: 26, isCurrentMonth: true, isToday: false },

  // Week 5: Sep 27 - Oct 03
  { dateKey: '2026-09-27', dayNumber: 27, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-28', dayNumber: 28, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-29', dayNumber: 29, isCurrentMonth: true, isToday: false },
  { dateKey: '2026-09-30', dayNumber: 30, isCurrentMonth: true, isToday: false, specialNote: 'Month-end Wrap' },
  { dateKey: '2026-10-01', dayNumber: 1, isCurrentMonth: false, isToday: false, monthLabel: 'Oct' },
  { dateKey: '2026-10-02', dayNumber: 2, isCurrentMonth: false, isToday: false, monthLabel: 'Oct' },
  { dateKey: '2026-10-03', dayNumber: 3, isCurrentMonth: false, isToday: false, monthLabel: 'Oct' },
];

export const mockDayInspectorData: DayInspectorData = {
  dateTitle: 'Friday, September 11, 2026',
  subtitle: 'Synchronized telemetry across active operational vectors.',
  tasksDone: 3,
  tasksPending: 2,
  tasksList: [
    {
      id: 'task-cal-1',
      title: 'API Integration — Anchor Sync engine endpoint',
      isCompleted: true,
    },
    {
      id: 'task-cal-2',
      title: 'Gym — Heavy deadlifts & mobility sprint',
      isCompleted: true,
    },
    {
      id: 'task-cal-3',
      title: 'Investment yield recalculation for Vault',
      isCompleted: true,
    },
    {
      id: 'task-cal-4',
      title: 'Sovereign Architecture Draft review',
      isCompleted: false,
    },
    {
      id: 'task-cal-5',
      title: 'Evening cold soak & reading session',
      isCompleted: false,
    },
  ],
  ledgerItems: [
    { category: 'Food & Dining', amount: 850 },
    { category: 'Transit', amount: 300 },
    { category: 'Sub (Cloud)', amount: 150 },
  ],
  ledgerTotal: -1300,
  journalQuote: 'Stabilizing the core pipelines today. Focused energy towards quiet structural depth instead of noisy output. Restraint is power.',
  journalTime: 'Inscribed 07:42 AM',
  cadenceDelta: '+2.4% to Reserve',
};

export const mockSovereignGoals: SovereignGoal[] = [
  {
    id: 'goal-capital-reserve',
    title: 'Annual Capital Reserve: Rs. 100,000',
    subtitle: 'Target horizon: Dec 31, 2026',
    targetHorizon: 'Dec 31, 2026',
    progressPercentage: 72,
    achievedMetric: 'Rs. 72,000 achieved',
    gapMetric: 'Gap: Rs. 28,000',
    meterColor: '#111C2E',
  },
  {
    id: 'goal-nextjs-mastery',
    title: 'Next.js 15 Full Systems Mastery',
    subtitle: 'Architecture, Turbopack & Server actions',
    targetHorizon: 'Q4 2026',
    progressPercentage: 70,
    achievedMetric: '14 of 20 modules completed',
    gapMetric: '6 remaining',
    meterColor: '#40617E',
  },
  {
    id: 'goal-physical-resilience',
    title: 'Physical Resilience & Health',
    subtitle: 'Zone 2 Cardio & Resistance cadence',
    targetHorizon: 'Ongoing 2026',
    progressPercentage: 82,
    achievedMetric: '18 of 22 sessions logged this month',
    gapMetric: 'Cadence on track',
    meterColor: '#334155',
  },
];

export const mockTemporalHealth: TemporalHealthMetrics = {
  monthName: 'September 2026',
  operationalEquilibriumTitle: 'September Operational Equilibrium',
  operationalEquilibriumSubtext: 'Cadence holds 91.4% task fidelity and net reserve accretion.',
  tasksResolvedCount: 41,
  tasksTotalCount: 48,
  netBalanceMtd: 18340,
  currency: 'INR',
};

