import {
  Account,
  Transaction,
  BudgetEnvelope,
  DailyTask,
  TodayDebitItem,
  OutflowSector,
  CashflowVelocity,
  RecurringObligation,
  MindsetGoalAnchor,
  ExecutiveOverviewData,
} from '@/types/models';

export const mockAccounts: Account[] = [
  {
    id: 'acc-hdfc-4092',
    name: 'Operating Checking',
    type: 'checking',
    institution: 'HDFC Bank',
    accountNumberMasked: '•••• 4092',
    balance: 42500,
    currency: 'INR',
    status: 'active',
    trendLabel: '+2.4% vs last week',
    lastReconciledAt: '2026-09-30T18:00:00Z',
    updatedAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'acc-vault-0012',
    name: 'Physical Vault',
    type: 'cash',
    institution: 'Safe Deposit Reserve',
    accountNumberMasked: '•••• 0012',
    balance: 15200,
    currency: 'INR',
    status: 'reconciled',
    trendLabel: 'Stable allocation',
    lastReconciledAt: '2026-09-28T12:00:00Z',
    updatedAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'acc-tbill-8831',
    name: 'High-Yield Liquid Vault',
    type: 'savings',
    institution: 'Treasury Bills & Liquid Funds',
    accountNumberMasked: '•••• 8831',
    balance: 40000,
    currency: 'INR',
    status: 'active',
    trendLabel: '+4.2% APY Yield',
    lastReconciledAt: '2026-09-30T18:00:00Z',
    updatedAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'acc-amex-1042',
    name: 'Amex Platinum Card',
    type: 'credit',
    institution: 'American Express',
    accountNumberMasked: '•••• 1042',
    balance: -18500,
    currency: 'INR',
    creditLimit: 150000,
    paymentDueDate: '2026-10-05',
    status: 'active',
    trendLabel: '12% Utilized',
    lastReconciledAt: '2026-10-01T06:00:00Z',
    updatedAt: '2026-10-01T08:30:00Z',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-001',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -380,
    currency: 'INR',
    flowType: 'outflow',
    category: 'food_dining',
    categoryLabel: 'Food & Dining',
    payeeOrPayer: 'Blue Tokai Coffee Roasters',
    note: 'Morning cortado & pour-over beans',
    date: '2026-10-01',
    time: '08:15',
    paymentMethod: 'upi',
    status: 'cleared',
    createdAt: '2026-10-01T08:15:00Z',
  },
  {
    id: 'tx-002',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -420,
    currency: 'INR',
    flowType: 'outflow',
    category: 'transport_transit',
    categoryLabel: 'Transport & Transit',
    payeeOrPayer: 'Uber Premium Transit',
    note: 'Client strategy meeting transfer',
    date: '2026-10-01',
    time: '09:30',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-10-01T09:30:00Z',
  },
  {
    id: 'tx-003',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -500,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'Kinokuniya Book Order',
    note: 'Architecture of Complex Systems text',
    date: '2026-10-01',
    time: '11:45',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-10-01T11:45:00Z',
  },
  {
    id: 'tx-004',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: 45000,
    currency: 'INR',
    flowType: 'inflow',
    category: 'consulting_inflow',
    categoryLabel: 'Consulting Inflow',
    payeeOrPayer: 'Lumina Labs Advisory',
    note: 'Q3 Enterprise Architecture Retainer',
    date: '2026-09-30',
    time: '14:00',
    paymentMethod: 'direct_deposit',
    status: 'cleared',
    createdAt: '2026-09-30T14:00:00Z',
  },
  {
    id: 'tx-005',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -3850,
    currency: 'INR',
    flowType: 'outflow',
    category: 'food_dining',
    categoryLabel: 'Food & Dining',
    payeeOrPayer: 'Nature Basket Organic Market',
    note: 'Weekly organic produce & provisions',
    date: '2026-09-30',
    time: '18:20',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-09-30T18:20:00Z',
  },
  {
    id: 'tx-006',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -24000,
    currency: 'INR',
    flowType: 'outflow',
    category: 'housing_utilities',
    categoryLabel: 'Housing & Utilities',
    payeeOrPayer: 'Central Urban Studio Lease',
    note: 'Residential lease payment - September',
    date: '2026-09-28',
    time: '10:00',
    paymentMethod: 'wire',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-28T10:00:00Z',
  },
  {
    id: 'tx-007',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -4200,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'AWS Cloud Services',
    note: 'Compute & Database Infrastructure',
    date: '2026-09-27',
    time: '15:30',
    paymentMethod: 'card',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-27T15:30:00Z',
  },
  {
    id: 'tx-008',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -2100,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'Bloomberg Terminal Lite',
    note: 'Financial research data feed',
    date: '2026-09-25',
    time: '09:00',
    paymentMethod: 'card',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-25T09:00:00Z',
  },
  {
    id: 'tx-009',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -11700,
    currency: 'INR',
    flowType: 'outflow',
    category: 'shopping_gear',
    categoryLabel: 'Shopping & Gear',
    payeeOrPayer: 'Bang & Olufsen Atelier',
    note: 'Studio sound acoustic equipment',
    date: '2026-09-24',
    time: '16:15',
    paymentMethod: 'card',
    status: 'cleared',
    createdAt: '2026-09-24T16:15:00Z',
  },
  {
    id: 'tx-010',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: -7800,
    currency: 'INR',
    flowType: 'outflow',
    category: 'health_wellness',
    categoryLabel: 'Health & Wellness',
    payeeOrPayer: 'Equinox Athletic Club',
    note: 'Quarterly athletic recovery & trainer',
    date: '2026-09-20',
    time: '07:30',
    paymentMethod: 'wire',
    status: 'cleared',
    createdAt: '2026-09-20T07:30:00Z',
  },
  {
    id: 'tx-011',
    accountId: 'acc-hdfc-4092',
    accountName: 'Operating Checking',
    amount: 75000,
    currency: 'INR',
    flowType: 'inflow',
    category: 'consulting_inflow',
    categoryLabel: 'Consulting Inflow',
    payeeOrPayer: 'Apex Capital Advisory',
    note: 'Executive Systems Architecture Audit',
    date: '2026-09-15',
    time: '11:00',
    paymentMethod: 'wire',
    status: 'cleared',
    createdAt: '2026-09-15T11:00:00Z',
  },
  {
    id: 'tx-012',
    accountId: 'acc-vault-0012',
    accountName: 'Physical Vault',
    amount: -2500,
    currency: 'INR',
    flowType: 'outflow',
    category: 'transport_transit',
    categoryLabel: 'Transport & Transit',
    payeeOrPayer: 'Regional Chauffeur Service',
    note: 'Airport transit round-trip',
    date: '2026-09-12',
    time: '06:00',
    paymentMethod: 'cash',
    status: 'reconciled',
    createdAt: '2026-09-12T06:00:00Z',
  },
  {
    id: 'tx-013',
    accountId: 'acc-amex-1042',
    accountName: 'Amex Platinum Card',
    amount: -365,
    currency: 'INR',
    flowType: 'outflow',
    category: 'knowledge_subs',
    categoryLabel: 'Knowledge & Subs',
    payeeOrPayer: 'Apple One Premier',
    note: 'Cloud storage and developer ecosystem',
    date: '2026-09-10',
    time: '12:00',
    paymentMethod: 'card',
    status: 'cleared',
    isRecurring: true,
    createdAt: '2026-09-10T12:00:00Z',
  },
];

export const mockOutflowSectors: OutflowSector[] = [
  {
    id: 'sector-food',
    category: 'food_dining',
    label: 'Food & Dining',
    percentage: 30,
    amount: 19500,
    currency: 'INR',
    color: '#5F9277', // Controlled Sage
    strokeDashArray: '188.5 440',
    strokeDashOffset: 0,
  },
  {
    id: 'sector-housing',
    category: 'housing_utilities',
    label: 'Housing & Utilities',
    percentage: 25,
    amount: 16250,
    currency: 'INR',
    color: '#40617E', // Slate Secondary
    strokeDashArray: '157.1 471.2',
    strokeDashOffset: -188.5,
  },
  {
    id: 'sector-shopping',
    category: 'shopping_gear',
    label: 'Shopping & Gear',
    percentage: 18,
    amount: 11700,
    currency: 'INR',
    color: '#C76D68', // Soft Coral
    strokeDashArray: '113.1 515.2',
    strokeDashOffset: -345.6,
  },
  {
    id: 'sector-transport',
    category: 'transport_transit',
    label: 'Transport & Transit',
    percentage: 15,
    amount: 9750,
    currency: 'INR',
    color: '#C4934A', // Warm Ochre
    strokeDashArray: '94.2 534.1',
    strokeDashOffset: -458.7,
  },
  {
    id: 'sector-health',
    category: 'health_wellness',
    label: 'Health & Wellness',
    percentage: 12,
    amount: 7800,
    currency: 'INR',
    color: '#508E8C', // Mineral Teal
    strokeDashArray: '75.4 552.9',
    strokeDashOffset: -552.9,
  },
];

export const mockBudgetEnvelopes: BudgetEnvelope[] = [
  {
    id: 'env-food',
    category: 'food_dining',
    label: 'Food & Dining',
    allocatedAmount: 22000,
    spentAmount: 19500,
    currency: 'INR',
    burnRateStatus: 'normal',
    burnPercentage: 88.6,
    bufferRemaining: 2500,
    cycle: 'September 2026',
    icon: 'restaurant',
  },
  {
    id: 'env-housing',
    category: 'housing_utilities',
    label: 'Housing & Utilities',
    allocatedAmount: 25000,
    spentAmount: 24000,
    currency: 'INR',
    burnRateStatus: 'alert',
    burnPercentage: 96.0,
    bufferRemaining: 1000,
    cycle: 'September 2026',
    icon: 'home',
  },
  {
    id: 'env-shopping',
    category: 'shopping_gear',
    label: 'Shopping & Gear',
    allocatedAmount: 12500,
    spentAmount: 11700,
    currency: 'INR',
    burnRateStatus: 'alert',
    burnPercentage: 93.6,
    bufferRemaining: 800,
    cycle: 'September 2026',
    icon: 'shopping_bag',
  },
  {
    id: 'env-knowledge',
    category: 'knowledge_subs',
    label: 'Knowledge & Subs',
    allocatedAmount: 8000,
    spentAmount: 6300,
    currency: 'INR',
    burnRateStatus: 'contained',
    burnPercentage: 78.8,
    bufferRemaining: 1700,
    cycle: 'September 2026',
    icon: 'auto_stories',
  },
];

export const mockDailyTasks: DailyTask[] = [
  {
    id: 'task-1',
    title: 'Review Q3 Tax Provisioning & T-Bill Roll',
    category: 'finance',
    categoryLabel: 'Finance',
    priority: 'high',
    isCompleted: true,
    dueInfo: 'Completed 08:30 AM',
    createdAt: '2026-10-01T07:00:00Z',
    completedAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'task-2',
    title: 'Approve Lumina Labs Architectural Handoff',
    category: 'work',
    categoryLabel: 'Engineering',
    priority: 'high',
    isCompleted: true,
    dueInfo: 'Completed 09:15 AM',
    createdAt: '2026-10-01T07:15:00Z',
    completedAt: '2026-10-01T09:15:00Z',
  },
  {
    id: 'task-3',
    title: 'Reconcile HDFC & Amex Statement Feeds',
    category: 'finance',
    categoryLabel: 'Finance',
    priority: 'high',
    isCompleted: true,
    dueInfo: 'Completed 10:00 AM',
    createdAt: '2026-10-01T07:30:00Z',
    completedAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Deep Work: Anchor OS Component Architecture',
    category: 'work',
    categoryLabel: 'Engineering',
    priority: 'medium',
    isCompleted: false,
    dueInfo: 'Due 4:00 PM',
    createdAt: '2026-10-01T08:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Evening Mobility & Sprint Session',
    category: 'personal',
    categoryLabel: 'Wellness',
    priority: 'low',
    isCompleted: false,
    dueInfo: 'Due 6:30 PM',
    createdAt: '2026-10-01T08:00:00Z',
  },
];

export const mockTodayDebits: TodayDebitItem[] = [
  {
    id: 'debit-1',
    title: 'Blue Tokai Coffee Roasters',
    category: 'Food & Dining',
    paymentMethod: 'UPI • HDFC',
    amount: 380,
    currency: 'INR',
    time: '08:15 AM',
    icon: 'local_cafe',
  },
  {
    id: 'debit-2',
    title: 'Uber Premium Transit',
    category: 'Transport',
    paymentMethod: 'Card • Amex',
    amount: 420,
    currency: 'INR',
    time: '09:30 AM',
    icon: 'directions_car',
  },
  {
    id: 'debit-3',
    title: 'Kinokuniya Book Order',
    category: 'Knowledge',
    paymentMethod: 'Card • HDFC',
    amount: 500,
    currency: 'INR',
    time: '11:45 AM',
    icon: 'menu_book',
  },
];

export const mockMindsetGoal: MindsetGoalAnchor = {
  quote: 'Discipline is choosing between what you want now and what you want most.',
  quoteAuthor: 'Auguste Comte / Vance Journal',
  entryTime: 'Logged Today at 07:15 AM',
  goalTitle: 'Annual Tactical Reserve Fund',
  targetAmount: 100000,
  currentAmount: 72000,
  achievedPercentage: 72,
  targetDate: 'Dec 31, 2026',
};

export const mockCashflowVelocity: CashflowVelocity = {
  cycleDay: 21,
  cycleTotalDays: 30,
  totalInflow: 120000,
  totalOutflow: 65000,
  netSavings: 55000,
  retentionRate: 45.8,
  targetRetentionRate: 50.0,
  inflowCount: 3,
  outflowCount: 38,
  hotspots: [
    {
      id: 'hotspot-1',
      title: 'Dining out velocity',
      metric: '+18% vs 30-day baseline',
      severity: 'warning',
    },
    {
      id: 'hotspot-2',
      title: 'Ad hoc ride-hailing pace',
      metric: 'Rs. 2,100 / week velocity',
      severity: 'info',
    },
    {
      id: 'hotspot-3',
      title: 'Upcoming SaaS renewals',
      metric: '2 services renewing in 7 days',
      severity: 'warning',
    },
  ],
};

export const mockRecurringObligations: RecurringObligation[] = [
  {
    id: 'rec-1',
    name: 'AWS Cloud Services',
    amount: 4200,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 4 days',
    status: 'alert',
    category: 'knowledge_subs',
    icon: 'cloud',
  },
  {
    id: 'rec-2',
    name: 'Bloomberg Terminal Lite',
    amount: 2100,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 12 days',
    status: 'upcoming',
    category: 'knowledge_subs',
    icon: 'query_stats',
  },
  {
    id: 'rec-3',
    name: 'Residential Lease - Urban Studio',
    amount: 24000,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 28 days',
    status: 'cleared',
    category: 'housing_utilities',
    icon: 'apartment',
  },
  {
    id: 'rec-4',
    name: 'Apple One Premier Ecosystem',
    amount: 365,
    currency: 'INR',
    billingCycle: 'monthly',
    renewalNotice: 'Renews in 8 days',
    status: 'upcoming',
    category: 'knowledge_subs',
    icon: 'devices',
  },
];

export const mockOverviewData: ExecutiveOverviewData = {
  greeting: 'Good morning, Alex.',
  userName: 'Alex Vance',
  systemStatus: 'steady',
  dateDisplay: 'Thursday, October 1, 2026',
  totalLiquidity: 79200,
  liquidityTrendPercent: 4.2,
  currency: 'INR',
  monthlyInflow: 120000,
  monthlyInflowTrendPercent: 8.5,
  inflowSourcesCount: 3,
  totalExpenses: 65000,
  expensesBurnRatePercent: 81.2,
  netRetained: 55000,
  retentionRatePercent: 45.8,
  outflowSectors: mockOutflowSectors,
  totalSpent: 65000,
  budgetCap: 70000,
  budgetEnvelopes: mockBudgetEnvelopes,
  dailyTasks: mockDailyTasks,
  todayDebits: mockTodayDebits,
  mindsetGoal: mockMindsetGoal,
};
